name: Check Links

on:
  push:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.html'
